# This workflow renders all Markdown documents into a HTML website.

name: 'Build the website'

on:
  # re-render the website every time new changes are pushed
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # checkout the `master` branch
      - name: 'Checkout `master`'
        uses: actions/checkout@v2.3.4

      # prepare the `gh-pages` branch to publish the repository as a website
      - name: 'Checkout `gh-pages` into a separate directory'
        uses: actions/checkout@v2.3.4
        with:
          path: 'dist'
          ref: 'gh-pages'

      # use this action to render all Markdown documents into HTML documents
      - name: 'Render the repository as a website'
        uses: 'jerry-sky/vyrow@v0.7.0'
        with:
          # copy all files from the master branch to the `dist` directory
          # to make all files visible on the website;
          # this option is turned off by default,
          # so you can cherry-pick yourself only those files
          # that you want to publish
          copy-from: '.'
          website-root: '/til/'

      # get current time to mark it in the deployment commit message
      - name: 'Get current time'
        uses: gerred/current-time@v1.0.0
        id: current-time

      # deploy the result to the GH Pages branch
      - name: push the changes
        uses: EndBug/add-and-commit@v7.2.1
        with:
          message: "deployed on ${{ steps.current-time.outputs.time }}"
          branch: 'gh-pages'
          cwd: './dist/'
          add: '*'
          default_author: github_actions
