# This workflow renders all Markdown documents into a HTML website.

name: 'Build the website'

on:
  push:
    branches: [master]

jobs:

  update-readme:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run script file
      run: |
         chmod +x "${GITHUB_WORKSPACE}/.github/update-readme.sh"
         "${GITHUB_WORKSPACE}/.github/update-readme.sh"
      shell: bash

  build-pages:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout `master`'
        uses: actions/checkout@v2.3.4

      - name: 'Checkout `gh-pages` into a separate directory'
        uses: actions/checkout@v2.3.4
        with:
          path: 'dist'
          ref: 'gh-pages'

      - name: 'Render the repository as a website'
        uses: 'jerry-sky/vyrow@v0.7.0'
        with:
          copy-from: '.'
          website-root: '/til/'

      - name: 'Get current time'
        uses: gerred/current-time@v1.0.0
        id: current-time

      - name: push the changes
        uses: EndBug/add-and-commit@v7.2.1
        with:
          message: "deployed on ${{ steps.current-time.outputs.time }}"
          branch: 'gh-pages'
          cwd: './dist/'
          add: '*'
          default_author: github_actions
